#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

local_branch="$(git rev-parse --abbrev-ref HEAD)"

echo $local_branch

validate_branch_name() {
    local branch_name="$1"
    local pattern="^[A-Z]+_\d+_[a-z_]+$"

    if [[ $branch_name =~ $pattern ]]; then
        echo "Branch name '$branch_name' matches the pattern."
    else
        echo "Branch name '$branch_name' does not match the pattern."
    fi
}


validate_branch_name "$local_branch"

 